// <auto-generated />
using System;
using BinanceBotDb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BinanceBotDb.Migrations
{
    [DbContext(typeof(BinanceBotDbContext))]
    [Migration("20220324091145_FixedEventTemplates")]
    partial class FixedEventTemplates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BinanceBotDb.Models.BalanceChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount")
                        .HasComment("Amount of change in USDT");

                    b.Property<string>("Coin")
                        .HasColumnType("text")
                        .HasColumnName("coin")
                        .HasComment("Coin name");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date")
                        .HasComment("Balance change date");

                    b.Property<int>("IdDirection")
                        .HasColumnType("integer")
                        .HasColumnName("id_direction")
                        .HasComment("1 - Deposit \n2 - Withdraw");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("t_balance_changes");

                    b
                        .HasComment("User balance deposits and withdrawals");
                });

            modelBuilder.Entity("BinanceBotDb.Models.Directories.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("Caption")
                        .HasComment("Order status caption");

                    b.HasKey("Id");

                    b.ToTable("t_order_status");

                    b
                        .HasComment("Order status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Caption = "NEW"
                        },
                        new
                        {
                            Id = 2,
                            Caption = "CANCELLED"
                        },
                        new
                        {
                            Id = 3,
                            Caption = "FILLED"
                        });
                });

            modelBuilder.Entity("BinanceBotDb.Models.Directories.OrderType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("Caption")
                        .HasComment("Order type caption");

                    b.HasKey("Id");

                    b.ToTable("t_order_types");

                    b
                        .HasComment("Order types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Caption = "LIMIT"
                        },
                        new
                        {
                            Id = 2,
                            Caption = "MARKET"
                        },
                        new
                        {
                            Id = 3,
                            Caption = "STOP_LOSS"
                        });
                });

            modelBuilder.Entity("BinanceBotDb.Models.Directories.TradeMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Caption")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("caption")
                        .HasComment("Caption");

                    b.HasKey("Id");

                    b.ToTable("t_trade_modes");

                    b
                        .HasComment("Trade modes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Caption = "auto"
                        },
                        new
                        {
                            Id = 2,
                            Caption = "semiAuto"
                        });
                });

            modelBuilder.Entity("BinanceBotDb.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date")
                        .HasComment("Дата совершения события");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read")
                        .HasComment("Shows if event was read by user or not");

                    b.Property<string>("Text")
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)")
                        .HasColumnName("text")
                        .HasComment("Event text");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("t_events");

                    b
                        .HasComment("User/application event log");
                });

            modelBuilder.Entity("BinanceBotDb.Models.EventTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Template")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("template")
                        .HasComment("Template text");

                    b.HasKey("Id");

                    b.ToTable("t_event_templates");

                    b
                        .HasComment("Event log text templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Template = "Создан ордер на {0} торговой пары {1} в количестве {2} шт. по курсу {3} USDT на сумму {4} USDT. \n Способ: {5}. \n  Дата: {6}"
                        },
                        new
                        {
                            Id = 2,
                            Template = "Произошла ошибка при создании ордера на {0} торговой пары {1} в количестве {2} шт. по курсу {3} USDT на сумму {4} USDT. \n Текст ошибки: {5} \n Способ: {6}. \n Дата: {7}"
                        },
                        new
                        {
                            Id = 3,
                            Template = "Совершена {0} торговой пары {1} в количестве {2} шт. по курсу {3} USDT на сумму {4} USDT. \n Ордер выполнен. \n Дата: {5}"
                        },
                        new
                        {
                            Id = 4,
                            Template = "Произошла отмена ордера на {0} торговой пары {1} в количестве {2} шт. по курсу {3} USDT на сумму {4} USDT. \n Способ: {5} Дата: {6}"
                        },
                        new
                        {
                            Id = 5,
                            Template = "Произошла ошибка при отмене ордера на {0} торговой пары {1} в количестве {2} шт. по курсу {3} USDT на сумму {4} USDT. \n Текст ошибки: {5} \n Способ: {6}. \n Дата: {7}"
                        },
                        new
                        {
                            Id = 6,
                            Template = "Произошла ошибка при чтении ответа от биржи при {0} торговой пары {1} в количестве {2} шт. по курсу {3} USDT. \n Текст ошибки: {4} \n Способ: {5}. \n Дата: {6}"
                        },
                        new
                        {
                            Id = 7,
                            Template = "Автоматическая торговля {0}. \n Дата: {1}"
                        },
                        new
                        {
                            Id = 8,
                            Template = "Запрошена продажа всей криптовалюты на аккаунте. \n Дата: {0}"
                        });
                });

            modelBuilder.Entity("BinanceBotDb.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClientOrderId")
                        .HasColumnType("text")
                        .HasColumnName("client_order_id")
                        .HasComment("Exchange inner id");

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_closed")
                        .HasComment("Order closing date");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_created")
                        .HasComment("Order creation date");

                    b.Property<int>("IdCreationType")
                        .HasColumnType("integer")
                        .HasColumnName("id_creation_type")
                        .HasComment("1 - Auto\n2 - Manual");

                    b.Property<int>("IdOrderStatus")
                        .HasColumnType("integer")
                        .HasColumnName("id_order_status")
                        .HasComment("Order status (NEW, CLOSED, FILLED, etc)");

                    b.Property<int>("IdSide")
                        .HasColumnType("integer")
                        .HasColumnName("id_side")
                        .HasComment("1 - Buy\n2 - Sell");

                    b.Property<int>("IdType")
                        .HasColumnType("integer")
                        .HasColumnName("id_type")
                        .HasComment("1 - Limit\n2 - Market");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id")
                        .HasComment("Exchange inner id");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price")
                        .HasComment("Order price in secondary asset of trading pair");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity")
                        .HasComment("Amount of base asset");

                    b.Property<double>("QuoteOrderQty")
                        .HasColumnType("double precision")
                        .HasColumnName("quote_order_qty")
                        .HasComment("Amount of secondary asset");

                    b.Property<string>("Symbol")
                        .HasColumnType("text")
                        .HasColumnName("symbol")
                        .HasComment("Trade pair");

                    b.Property<string>("TimeInForce")
                        .HasColumnType("text")
                        .HasColumnName("time_in_force")
                        .HasComment("GTC, IOC, FOK");

                    b.HasKey("Id");

                    b.HasIndex("IdOrderStatus");

                    b.HasIndex("IdType");

                    b.ToTable("t_orders");

                    b
                        .HasComment("Trade orders");
                });

            modelBuilder.Entity("BinanceBotDb.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date")
                        .HasComment("Request date");

                    b.Property<long>("ElapsedMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("elapsed_ms")
                        .HasComment("Request lifetime");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user")
                        .HasComment("Request user id");

                    b.Property<string>("Ip")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("ip")
                        .HasComment("Request ip address");

                    b.Property<string>("Login")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("login")
                        .HasComment("Request user login");

                    b.Property<string>("Referer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referer")
                        .HasComment("Request referer");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("request_method")
                        .HasComment("Request http method");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("request_path")
                        .HasComment("Request path");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasComment("Request http status");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("t_request_log");

                    b
                        .HasComment("Application http request log");
                });

            modelBuilder.Entity("BinanceBotDb.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ApiKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("api_key")
                        .HasComment("api key");

                    b.Property<int>("IdTradeMode")
                        .HasColumnType("integer")
                        .HasColumnName("id_trade_mode")
                        .HasComment("Selected trade mode");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<bool>("IsTradeEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_trade_enabled")
                        .HasComment("Trade on/off");

                    b.Property<int>("LimitOrderRate")
                        .HasColumnType("integer")
                        .HasColumnName("limit_order_rate")
                        .HasComment("Amount of percents from highest price to place limit order");

                    b.Property<string>("SecretKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("secret_key")
                        .HasComment("secret key");

                    b.HasKey("Id");

                    b.HasIndex("IdTradeMode");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("t_settings");

                    b
                        .HasComment("Application trade settings");
                });

            modelBuilder.Entity("BinanceBotDb.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_created");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email")
                        .HasComment("Email");

                    b.Property<int?>("IdRole")
                        .HasColumnType("integer")
                        .HasColumnName("id_role");

                    b.Property<string>("Login")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name")
                        .HasComment("Name");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password")
                        .HasComment("Password hash");

                    b.Property<string>("Surname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("surname")
                        .HasComment("Surname");

                    b.HasKey("Id");

                    b.HasIndex("IdRole");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("t_users");

                    b
                        .HasComment("Users");
                });

            modelBuilder.Entity("BinanceBotDb.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Caption")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("caption")
                        .HasComment("Caption");

                    b.HasKey("Id");

                    b.ToTable("t_user_roles");

                    b
                        .HasComment("User roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Caption = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Caption = "User"
                        });
                });

            modelBuilder.Entity("BinanceBotDb.Models.BalanceChange", b =>
                {
                    b.HasOne("BinanceBotDb.Models.User", "User")
                        .WithMany("BalanceChanges")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinanceBotDb.Models.Event", b =>
                {
                    b.HasOne("BinanceBotDb.Models.User", "User")
                        .WithMany("EventLog")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinanceBotDb.Models.Order", b =>
                {
                    b.HasOne("BinanceBotDb.Models.Directories.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("IdOrderStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinanceBotDb.Models.Directories.OrderType", "OrderType")
                        .WithMany("Orders")
                        .HasForeignKey("IdType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderStatus");

                    b.Navigation("OrderType");
                });

            modelBuilder.Entity("BinanceBotDb.Models.Request", b =>
                {
                    b.HasOne("BinanceBotDb.Models.User", "User")
                        .WithMany("RequestLog")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinanceBotDb.Models.Settings", b =>
                {
                    b.HasOne("BinanceBotDb.Models.Directories.TradeMode", "TradeMode")
                        .WithMany("Settings")
                        .HasForeignKey("IdTradeMode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinanceBotDb.Models.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("BinanceBotDb.Models.Settings", "IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeMode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinanceBotDb.Models.User", b =>
                {
                    b.HasOne("BinanceBotDb.Models.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("IdRole");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BinanceBotDb.Models.Directories.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BinanceBotDb.Models.Directories.OrderType", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BinanceBotDb.Models.Directories.TradeMode", b =>
                {
                    b.Navigation("Settings");
                });

            modelBuilder.Entity("BinanceBotDb.Models.User", b =>
                {
                    b.Navigation("BalanceChanges");

                    b.Navigation("EventLog");

                    b.Navigation("RequestLog");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("BinanceBotDb.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
